in_dim: 768 #1024 #768 #384
mood_dim: -1
out_dim: 1280
latent_dim: 512
n_layer: 4

n_eig: 64
flag_loss: 1.0
negative_sample_loss: 1.0
recon_loss: 1.0

log_dir: /tmp/logs/
name: debug

steps: 1000
batch_size: 8
lr: 0.001
